### GET request with a header
POST http://127.0.0.1:8088/createPlayer
Accept: application/json




###
POST http://127.0.0.1:8088/login
Content-Type: application/json

{
  "openId": "998",
  "playerId": 12345
}